server:
  port: 8080
  servlet:
    context-path:
      encoding:
        charset: UTF-8

spring:
  application:
    name: test
  datasource:
    url: jdbc:postgresql://localhost:5430/testdb
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # ??? create-drop, validate ? ??????????? ?? ????? ????
    show-sql: true    # ?????????? SQL-??????? ? ?????
    properties:
      hibernate:
        format_sql: true  # ????????????? SQL-??????? ??? ???????? ??????
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5430/testdb}
    locations: ${FLYWAY_LOCATION:classpath:db/migration/postgres}
    baseline-on-migrate: true
    enabled: ${FLYWAY_ENABLED:true}
    user: ${DATASOURCE_USER:test}
    password: ${DATASOURCE_PASSWORD:test}
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:209715200}
      max-request-size: ${MAX_REQUEST_SIZE:209715200}
  security:
    jwt:
      secret: secret
      expiration: 3600000 # ????? ????? ?????? ? ????????????? (1 ???)

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    root-after-startup: ${LOG_LEVEL_AFTER_STARTUP:INFO}
    com.example.test: ${APP_LOG_LEVEL:DEBUG}
    org:
      hibernate:
        SQL: DEBUG     # ??????????? SQL-????????
        type: TRACE    # ??????????? ?????????? ????????
